### ISSUE TITLE
rightSize?

### ISSUE THREAD

**Issue by pb-cdunn** [jackhftang/lrucache#4]
https://nim-lang.org/docs/tables.html#rightSize%2CNatural

`rightSize()` is deprecated. I think I see that used here.

(I was just browsing this source-code after reading https://forum.nim-lang.org/t/6931 )

**Comment by jackhftang** [comment]
This issue needs a fix from compiler. In the meantime, the rightSize deprecation notice do not affect the functionality. 

## Reference
- https://forum.nim-lang.org/t/6958
- https://github.com/nim-lang/Nim/issues/15650

**Comment by jackhftang** [comment]
fixed in 1.1.1

**update:** wrong fix

**Comment by jackhftang** [comment]
fixed in 1.1.3
